---
- name: "Deploy a jar file"
  hosts: all
  tasks:
    - name: "Pull docker images"
      command: "docker-compose -f docker-compose.yml pull"
    - name: "Start docker compose"
      command: "docker-compose -f docker-compose.yml up -d"
